### PR TITLE
Single Setpoint Mode

### PR DESCRIPTION
**Pull request by PeteRager**
Add support for retrieving the correct setpoints when in single setpoint mode and for other system Modes.  Add units tests.

### CODE REVIEW

**Comment by PeteRager** [comment]
@hufman - please give this a review - these methods are used from the integration to retrieve the current setpoint, i also have some changes there that I will create a pull request for - that may not happen until tomorrow.

**Comment by PeteRager** [comment]
Also note, some formatting changes.  HA uses Black as their formatting standard, hence I've adopted that also for the API and the Integration.  End-goal is to put the integration into HA.

**Comment by hufman** [comment]
If this is only meant to view the set point, this looks great. I'd separately recommend making a set of `getCoolSP` and `getHeatSP` accessor functions to match the `setCoolSP`/`setHeatSP` setters (and then the integration can compare those for equality to toggle the HA feature flag for split setpoints), instead of needing the integration to reach directly into the zone.csp/hsp variable, but that's not related to this change :)

**Comment by PeteRager** [comment]
Just created a pull request for the HA component for the Read Side for Single Setpoints as well as resolving the other issue.

https://github.com/PeteRager/lennoxs30/pull/66

**Comment by PeteRager** [comment]
> If this is only meant to view the set point, this looks great. I'd separately recommend making a set of `getCoolSP` and `getHeatSP` accessor functions to match the `setCoolSP`/`setHeatSP` setters (and then the integration can compare those for equality to toggle the HA feature flag for split setpoints), instead of needing the integration to reach directly into the zone.csp/hsp variable, but that's not related to this change :)

Yeah, that's a good point.  I'll make that change.

**Pull request merged**
